# Generated by Django 3.2.8 on 2022-02-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('month', models.CharField(max_length=9)),
                ('day', models.CharField(max_length=9)),
                ('year', models.CharField(max_length=4)),
                ('time', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=46)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
    ]
